# Generated by Django 5.2.7 on 2025-10-16 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteLaboratorio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_examen', models.CharField(max_length=150)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_resultado', models.DateField(blank=True, null=True)),
                ('resultados', models.TextField()),
                ('analizado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('consulta_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_laboratorio_solicitados', to='Api_Clinica.consultamedica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_laboratorio', to='Api_Clinica.paciente')),
            ],
            options={
                'verbose_name': 'Reporte de Laboratorio',
                'verbose_name_plural': 'Reportes de Laboratorio',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
